Prevent use of constant challenge value
oauthstuff/draft-ietf-oauth-security-topics pull request #86
Opened 2023-11-07 11:26 UTC by selfissued

... as discussed with @aaronpk and @danielfett  at IETF 118.

2023-11-07 12:09 UTC, panva commented
I am surprised to see yet another attempt to add a measure that requires state synchronization across the deployment.

I wish there was more language with maybe a recommendations about how vigorous this mechanism should be, at which step it should be checking to remain effective, etc.

2023-11-07 17:01 UTC, jogu commented
I agree with Filip. I don't think it's necessary to detect every case of re-use. This is really a measure to stop client developers deploying clients into production systems that have poor security, and a 'best efforts' style detection that will eventually stop some requests from clients that are reusing nonces/PKCE challenges is probably okay.

I also think it should not be explicit about it being the PKCE challenge - some authorization servers may prefer to detect reuse of code_verifier instead (they're almost equivalent statements, but referring to PKCE challenges may imply that the detection should be at the authorization endpoint).

2023-11-28 20:43 UTC, selfissued commented
What if I changed the language to:
> Authorization servers SHOULD detect and prevent the use of constant PKCE challenge or OpenID Connect `nonce` values.

Then synchronization isn't required.

I believe we need to say something about this possibility, which actually occurs in practice.  If you have different language in mind, please propose text.

2023-12-19 03:55 UTC, bc-pi commented
Perhaps something like this might be a more realistic statement and be less objectionable?

> Authorization servers are encouraged to make a reasonable effort at detecting and preventing the use of constant PKCE challenge or OpenID Connect nonce values.

2023-12-19 04:27 UTC, selfissued commented on recommendations.md
> +PKCE challenge or OpenID Connect `nonce` values.
```suggestion
Authorization servers SHOULD detect and prevent the use of constant PKCE challenge or OpenID Connect `nonce` values.
```

2023-12-19 04:29 UTC, selfissued commented
I applied the suggested wording to the PR.

2023-12-19 04:32 UTC, bc-pi approved these changes

2023-12-19 08:31 UTC, panva approved these changes

2023-12-19 08:32 UTC, panva requested changes
Ah no, it seems brian's suggestion is not the one in the PR at the moment.

2023-12-19 08:48 UTC, bc-pi requested changes

2023-12-19 08:48 UTC, bc-pi commented on recommendations.md
> +Authorization servers SHOULD detect and prevent the use of constant PKCE challenge or OpenID Connect `nonce` values.
```suggestion
Authorization servers are encouraged to make a reasonable effort at detecting and
preventing the use of constant PKCE challenge or OpenID Connect nonce values.
```

2023-12-19 08:53 UTC, bc-pi commented
> Ah no, it seems brian's suggestion is not the one in the PR at the moment. It is in my opinion preferable.

Thanks for catching that Filip. I'd overlooked it in my flu induced and sleep deprived stupor.

2023-12-20 01:09 UTC, selfissued commented on recommendations.md
> +preventing the use of constant PKCE challenge or OpenID Connect nonce values.
```suggestion
preventing the use of constant PKCE challenge or OpenID Connect `nonce` values.
```

2023-12-20 01:10 UTC, selfissued commented
I've applied Brian's wording suggestion.

2023-12-20 01:55 UTC, bc-pi approved these changes

2023-12-20 07:15 UTC, panva approved these changes

2023-12-20 07:59 UTC, danielfett approved these changes

2023-12-20 08:00 UTC, merged